# NGINX module name (must match `ngx_module_name` in `config` and the
# `pub static mut ngx_http_otel_module: ngx_module_t` symbol in src/lib.rs).
MODULE_NAME	= ngx_http_otel_module
# Cargo target name (must match [lib] name in Cargo.toml; cargo produces
# libngx_http_otel_module.{a,dylib,so} from this).
TARGET_NAME	= ngx_http_otel_module

# build/build-%.mk: debug, release, sanitize
BUILD		?= debug
# Test target. For Phase A this is our existing bash integration scripts;
# Phase B will switch this to a t/ directory of Test::Nginx .t files.
TESTS		?= tests/integration/run.sh \
		   tests/integration/run_reload.sh \
		   tests/integration/run_endpoint_change.sh
NGX_CARGO	?= cargo

# nginx configure base flags. Phase 1.1 needs --with-compat (for loading a
# separately-built dynamic module) and --with-http_stub_status_module (for
# the ngx_stat_* atomics our StubStatusSource reads). Phase 1.2 will add
# --with-http_ssl_module + --with-pcre etc.
NGINX_CONFIGURE_BASE	= \
	auto/configure \
		--with-compat \
		--with-http_stub_status_module

NGINX_SOURCE_DIR	?= ../nginx
# Upstream nginx-tests repo. Used by Test::Nginx in Phase B (`make full-test`).
# Default falls back to NGINX_SOURCE_DIR so compat-{gnu,posix}.mk's path
# resolution succeeds when the operator hasn't cloned nginx-tests yet.
# Override before running Phase B: NGINX_TESTS_DIR=../nginx-tests make full-test
# (clone https://github.com/nginx/nginx-tests there first).
NGINX_TESTS_DIR		?= $(NGINX_SOURCE_DIR)
NGINX_BUILD_DIR		?= $(CURDIR)/objs-$(BUILD)

TEST_NGINX_BINARY	= $(NGINX_BUILD_DIR)/nginx
TEST_NGINX_GLOBALS	+= env RUST_BACKTRACE;

# Shared library generated with --add-dynamic-module=.
NGINX_BUILT_MODULE	= $(NGINX_BUILD_DIR)/$(MODULE_NAME).so
# Shared libraries generated by cargo build (cdylib path; used as the
# load_module target by bash tests during the Phase A transition).
CARGO_DEBUG_MODULE	= target/debug/lib$(TARGET_NAME)$(SHLIB_EXT)
CARGO_RELEASE_MODULE	= target/release/lib$(TARGET_NAME)$(SHLIB_EXT)

# "build" always calls cargo and causes relinking.
# Clearing this var allows to skip the build step: "make test TEST_PREREQ="
TEST_PREREQ = build


.PHONY: all

all: ## Build, lint and test the module
all: build check test


# Conditionals via include, compatible with most implementations of make

# GNU make 3.81 or earlier
MAKE_FLAVOR:= gnu
# POSIX 2024, BSD, GNU make 3.82+, etc
MAKE_FLAVOR!= echo posix

include	build/compat-$(MAKE_FLAVOR).mk
include	build/build-$(BUILD).mk


# Set up environment propagation

BUILD_ENV	+= NGINX_SOURCE_DIR="$(NGINX_SOURCE_DIR)"
BUILD_ENV	+= NGINX_BUILD_DIR="$(NGINX_BUILD_DIR)"

TEST_ENV	+= RUST_BACKTRACE=1
TEST_ENV	+= TEST_NGINX_BINARY="$(TEST_NGINX_BINARY)"
TEST_ENV	+= TEST_NGINX_GLOBALS="$(TEST_NGINX_GLOBALS)"
# The bash tests in tests/integration/ read these directly.  Phase B's
# Test::Nginx ports will read TEST_NGINX_BINARY / TEST_NGINX_GLOBALS instead.
TEST_ENV	+= NGINX_SOURCE_DIR="$(NGINX_SOURCE_DIR)"
TEST_ENV	+= NGINX_BUILD_DIR="$(NGINX_BUILD_DIR)"


# Build targets

.PHONY: help build check unittest test full-test clean

help:
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*?## "}; /^[ a-zA-Z_-]+:.*?## .*$$/ {printf "%-16s %s\n", $$1, $$2}' \
		Makefile $(MAKEFILE_LIST) | sort -u
	@echo "Pass BUILD=<configuration> to any target for desired build configuration."
	@echo "Pass NGINX_SOURCE_DIR to specify path to your NGINX source checkout."

# Always rebuild targets managed by external build tool
.PHONY: $(CARGO_DEBUG_MODULE) $(CARGO_RELEASE_MODULE) $(NGINX_BUILT_MODULE) \
	$(TEST_NGINX_BINARY)

$(NGINX_BUILD_DIR)/Makefile: config config.make auto/rust
$(NGINX_BUILD_DIR)/Makefile: $(NGINX_SOURCE_DIR)/src/core/nginx.h
# auto/configure unconditionally generates $NGINX_SOURCE_DIR/Makefile, even for
# out-of-tree builds.  Preserve the original Makefile and restore it later.
	@-cd $(NGINX_SOURCE_DIR) && rm -f Makefile.bak \
		&& test -f Makefile && mv -f Makefile Makefile.bak
	cd $(NGINX_SOURCE_DIR) \
		&& $(BUILD_ENV) $(NGINX_CONFIGURE) --builddir=$(NGINX_BUILD_DIR) \
		&& rm -f $(NGINX_SOURCE_DIR)/Makefile
	@-mv $(NGINX_SOURCE_DIR)/Makefile.bak $(NGINX_SOURCE_DIR)/Makefile

$(TEST_NGINX_BINARY): $(NGINX_BUILD_DIR)/Makefile
	cd $(NGINX_SOURCE_DIR) \
		&& $(BUILD_ENV) $(MAKE) -f $(NGINX_BUILD_DIR)/Makefile binary

$(NGINX_BUILT_MODULE): $(NGINX_BUILD_DIR)/Makefile
	cd $(NGINX_SOURCE_DIR) \
		&& $(BUILD_ENV) $(MAKE) -f $(NGINX_BUILD_DIR)/Makefile modules

$(CARGO_DEBUG_MODULE): $(NGINX_BUILD_DIR)/Makefile
	$(BUILD_ENV) $(NGX_CARGO) build

$(CARGO_RELEASE_MODULE): $(NGINX_BUILD_DIR)/Makefile
	$(BUILD_ENV) $(NGX_CARGO) build --release

build: $(TEST_NGINX_BINARY) ## Build the module

check: $(NGINX_BUILD_DIR)/Makefile ## Check style and lint
	$(BUILD_ENV) $(NGX_CARGO) fmt --all -- --check
	$(BUILD_ENV) $(NGX_CARGO) clippy --all-targets --verbose -- -D warnings

unittest: $(NGINX_BUILD_DIR)/Makefile  ## Run unit-tests
	$(BUILD_ENV) $(NGX_CARGO) test --lib

# Phase A test target: invoke our existing bash integration scripts via the
# nginx binary we just built (TEST_NGINX_BINARY). Phase B replaces this with
# `prove -I $(NGINX_TESTS_DIR)/lib t/`.
test: $(TEST_PREREQ) ## Run the integration test suite
	@for t in $(TESTS); do \
		echo "==> $$t"; \
		env $(TEST_ENV) bash $$t || exit 1; \
	done

# Phase B will fill this in. For now it's an alias for `test`.
full-test: test ## Run module + nginx integration suites (Phase B)

clean: ## Cleanup everything
	rm -rf $(NGINX_BUILD_DIR)
	$(NGX_CARGO) clean

# ── OTel collector lifecycle (wraps test-harness/lib.sh) ────────────────────
# These targets manage the local OTel collector container the integration
# tests need.  `make test` does NOT depend on `collector-up` because each
# test script auto-starts the collector via test-harness/lib.sh; but
# operators can use these for explicit control.

HARNESS_DIR	= $(CURDIR)/test-harness

.PHONY: collector-up collector-down collector-status

collector-up: ## Start the local OTel collector (idempotent)
	@bash -c '. $(HARNESS_DIR)/lib.sh && ensure_collector_running'

collector-down: ## Stop the local OTel collector
	@bash -c '. $(HARNESS_DIR)/lib.sh && collector_down'

collector-status: ## Show local OTel collector status
	@bash -c '. $(HARNESS_DIR)/lib.sh && collector_status'

# GNU make convenience targets. Will be ignored by other implementations.

build-%: ## Build with the specified configuration. E.g. make build-sanitize.
	$(MAKE) build BUILD="$*"

test-%: ## Test with the specified configuration.
	$(MAKE) test BUILD="$*"
