# NGINX module name (must match `ngx_module_name` in `config` and the
# `pub static mut ngx_http_otel_module: ngx_module_t` symbol in src/lib.rs).
MODULE_NAME	= ngx_http_otel_module
# Cargo target name (must match [lib] name in Cargo.toml; cargo produces
# libngx_http_otel_module.{a,dylib,so} from this).
TARGET_NAME	= ngx_http_otel_module

# build/build-%.mk: debug, release, sanitize
BUILD		?= debug
# Test target. For Phase A this is our existing bash integration scripts;
# Phase B will switch this to a t/ directory of Test::Nginx .t files.
TESTS		?= tests/integration/run.sh \
		   tests/integration/run_reload.sh \
		   tests/integration/run_endpoint_change.sh \
		   tests/integration/run_traces.sh \
		   tests/integration/run_redirect_safe.sh \
		   tests/integration/run_a3_tls_e2e.sh \
		   tests/integration/run_b1_collector_cert_gauge.sh
NGX_CARGO	?= cargo

# nginx configure base flags. --with-compat is required for loading a
# separately-built dynamic module; --with-http_stub_status_module provides
# the ngx_stat_* atomics our StubStatusSource reads. The TLS-enabled build
# adds --with-http_ssl_module so bindgen sees the real ngx_ssl_s layout and
# ngx_http_ssl_module is emitted (required for cert-metrics in the TLS tests).
NGINX_CONFIGURE_BASE	= \
	auto/configure \
		--with-compat \
		--with-http_ssl_module \
		--with-http_stub_status_module

NGINX_SOURCE_DIR	?= ../nginx
# Upstream nginx-tests repo. Used by Test::Nginx in Phase B (`make full-test`).
# Default falls back to NGINX_SOURCE_DIR so compat-{gnu,posix}.mk's path
# resolution succeeds when the operator hasn't cloned nginx-tests yet.
# Override before running Phase B: NGINX_TESTS_DIR=../nginx-tests make full-test
# (clone https://github.com/nginx/nginx-tests there first).
NGINX_TESTS_DIR		?= $(NGINX_SOURCE_DIR)
NGINX_BUILD_DIR		?= $(CURDIR)/objs-$(BUILD)

TEST_NGINX_BINARY	= $(NGINX_BUILD_DIR)/nginx
TEST_NGINX_GLOBALS	+= env RUST_BACKTRACE;

# Shared library generated with --add-dynamic-module=.
NGINX_BUILT_MODULE	= $(NGINX_BUILD_DIR)/$(MODULE_NAME).so
# Shared libraries generated by cargo build (cdylib path; used as the
# load_module target by bash tests during the Phase A transition).
CARGO_DEBUG_MODULE	= target/debug/lib$(TARGET_NAME)$(SHLIB_EXT)
CARGO_RELEASE_MODULE	= target/release/lib$(TARGET_NAME)$(SHLIB_EXT)

# "build" always calls cargo and causes relinking.
# Clearing this var allows to skip the build step: "make test TEST_PREREQ="
TEST_PREREQ = build


.PHONY: all

all: ## Build, lint and test the module
all: build check test


# Conditionals via include, compatible with most implementations of make

# GNU make 3.81 or earlier
MAKE_FLAVOR:= gnu
# POSIX 2024, BSD, GNU make 3.82+, etc
MAKE_FLAVOR!= echo posix

include	build/compat-$(MAKE_FLAVOR).mk
include	build/build-$(BUILD).mk


# Set up environment propagation

BUILD_ENV	+= NGINX_SOURCE_DIR="$(NGINX_SOURCE_DIR)"
BUILD_ENV	+= NGINX_BUILD_DIR="$(NGINX_BUILD_DIR)"

# macOS: openssl-sys MUST link the SAME OpenSSL that nginx links (dynamic
# openssl@3), or the module carries its own incompatible OpenSSL and the
# Phase C cert walk silently enumerates ZERO certs from nginx's SSL_CTX
# objects (found via the demo 2026-06-12; the C2 review flagged the skew).
# Linux has one system OpenSSL, so this expands to nothing there.
# Flavor-neutral dual assignment (same idiom as MAKE_FLAVOR above): GNU make
# 3.81 (macOS system make) ignores `!=` and takes the `:=`/$(shell) line;
# POSIX-2024/GNU-4 makes take the `!=` line. Both compute the same string.
OPENSSL_BUILD_ENV := $(shell if [ "`uname -s`" = "Darwin" ] && [ -e /opt/homebrew/opt/openssl@3/lib/libssl.dylib ]; then echo "OPENSSL_DIR=/opt/homebrew/opt/openssl@3 OPENSSL_STATIC=0 OPENSSL_NO_VENDOR=1"; fi)
OPENSSL_BUILD_ENV != if [ "`uname -s`" = "Darwin" ] && [ -e /opt/homebrew/opt/openssl@3/lib/libssl.dylib ]; then echo "OPENSSL_DIR=/opt/homebrew/opt/openssl@3 OPENSSL_STATIC=0 OPENSSL_NO_VENDOR=1"; fi
BUILD_ENV	+= $(OPENSSL_BUILD_ENV)

TEST_ENV	+= RUST_BACKTRACE=1
TEST_ENV	+= TEST_NGINX_BINARY="$(TEST_NGINX_BINARY)"
TEST_ENV	+= TEST_NGINX_GLOBALS="$(TEST_NGINX_GLOBALS)"
# The bash tests in tests/integration/ read these directly.  Phase B's
# Test::Nginx ports will read TEST_NGINX_BINARY / TEST_NGINX_GLOBALS instead.
TEST_ENV	+= NGINX_BINARY="$(TEST_NGINX_BINARY)"
TEST_ENV	+= NGINX_SOURCE_DIR="$(NGINX_SOURCE_DIR)"
TEST_ENV	+= NGINX_BUILD_DIR="$(NGINX_BUILD_DIR)"


# Build targets

.PHONY: help build check doc-check install-hooks unittest unittest-release test full-test clean

help:
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*?## "}; /^[ a-zA-Z_-]+:.*?## .*$$/ {printf "%-16s %s\n", $$1, $$2}' \
		Makefile $(MAKEFILE_LIST) | sort -u
	@echo "Pass BUILD=<configuration> to any target for desired build configuration."
	@echo "Pass NGINX_SOURCE_DIR to specify path to your NGINX source checkout."

# Always rebuild targets managed by external build tool
.PHONY: $(CARGO_DEBUG_MODULE) $(CARGO_RELEASE_MODULE) $(NGINX_BUILT_MODULE) \
	$(TEST_NGINX_BINARY)

$(NGINX_BUILD_DIR)/Makefile: config config.make auto/rust
$(NGINX_BUILD_DIR)/Makefile: $(NGINX_SOURCE_DIR)/src/core/nginx.h
# auto/configure unconditionally generates $NGINX_SOURCE_DIR/Makefile, even for
# out-of-tree builds.  Preserve the original Makefile and restore it later.
	@-cd $(NGINX_SOURCE_DIR) && rm -f Makefile.bak \
		&& test -f Makefile && mv -f Makefile Makefile.bak
	cd $(NGINX_SOURCE_DIR) \
		&& $(BUILD_ENV) $(NGINX_CONFIGURE) --builddir=$(NGINX_BUILD_DIR) \
		&& rm -f $(NGINX_SOURCE_DIR)/Makefile
	@-mv $(NGINX_SOURCE_DIR)/Makefile.bak $(NGINX_SOURCE_DIR)/Makefile

$(TEST_NGINX_BINARY): $(NGINX_BUILD_DIR)/Makefile
	cd $(NGINX_SOURCE_DIR) \
		&& $(BUILD_ENV) $(MAKE) -f $(NGINX_BUILD_DIR)/Makefile binary

$(NGINX_BUILT_MODULE): $(NGINX_BUILD_DIR)/Makefile
	cd $(NGINX_SOURCE_DIR) \
		&& $(BUILD_ENV) $(MAKE) -f $(NGINX_BUILD_DIR)/Makefile modules

$(CARGO_DEBUG_MODULE): $(NGINX_BUILD_DIR)/Makefile
	$(BUILD_ENV) $(NGX_CARGO) build

$(CARGO_RELEASE_MODULE): $(NGINX_BUILD_DIR)/Makefile
	$(BUILD_ENV) $(NGX_CARGO) build --release

build: $(TEST_NGINX_BINARY) ## Build the module

check: $(NGINX_BUILD_DIR)/Makefile ## Check style and lint
	$(BUILD_ENV) $(NGX_CARGO) fmt --all -- --check
	$(BUILD_ENV) $(NGX_CARGO) clippy --all-targets --verbose -- -D warnings
	$(MAKE) doc-check

# `cargo clippy` does not run rustdoc lints, so the crate-root
# `#![deny(rustdoc::broken_intra_doc_links)]` is only enforced by an actual
# doc build. Treating rustdoc warnings as errors fails the build on any broken
# intra-doc link or other doc warning. --document-private-items so links in
# `//` -> `///` on non-pub items are checked too.
doc-check: $(NGINX_BUILD_DIR)/Makefile ## Build rustdoc with warnings as errors (checks intra-doc links)
	$(BUILD_ENV) RUSTDOCFLAGS="-D warnings" $(NGX_CARGO) doc --no-deps --document-private-items

install-hooks: ## Install the local pre-commit gate (sets git core.hooksPath)
	git config core.hooksPath .githooks
	@echo "Installed: core.hooksPath=.githooks — pre-commit now runs 'make check'."

unittest: $(NGINX_BUILD_DIR)/Makefile  ## Run unit-tests (debug profile, objs-debug tree)
	$(BUILD_ENV) $(NGX_CARGO) test --lib

unittest-release: ## Run unit-tests in release profile (objs-release tree; requires make build-release first)
	NGINX_SOURCE_DIR="$(NGINX_SOURCE_DIR)" \
	NGINX_BUILD_DIR="$(CURDIR)/objs-release" \
	$(OPENSSL_BUILD_ENV) \
	$(NGX_CARGO) test --release --lib

# Phase A test target: invoke our existing bash integration scripts via the
# nginx binary we just built (TEST_NGINX_BINARY). Phase B replaces this with
# `prove -I $(NGINX_TESTS_DIR)/lib t/`.
#
# test and full-test pin BUILD=release so the nginx binary, NGINX_BUILD_DIR,
# and the cargo --release artifact are all from the same release pairing.
# This prevents the A0.5 flavor-mismatch guard from firing and avoids
# poisoning target/release with a debug-tree build.
#
# Mechanism: sub-make ($(MAKE) BUILD=release) rather than target-specific
# variables, because target-specific vars cannot change which
# build/build-$(BUILD).mk is included (includes are parsed before any target
# runs).  Sub-make reruns make from scratch with BUILD=release in the
# environment, so the correct include file and NGINX_BUILD_DIR are used.
#
# If the user explicitly passes BUILD=... on the command line (e.g.
# `BUILD=debug make test` for a debug-pairing debug run), that value is
# respected: $(origin BUILD) = "command line" distinguishes an explicit user
# override from the default "file" value, and we skip the sub-make.
# NOTE: debug-pairing integration runs (`BUILD=debug make test`) write a
# release-profile nginx-sys artifact to target/release built against the
# debug nginx tree; run `cargo clean` before `make build-release` afterward
# (the A0.5 guard will flag the mismatch if you forget).
ifneq ($(origin BUILD),command line)
test: ## Run the integration test suite (pins BUILD=release; use BUILD=debug make test for a debug-pairing run)
	$(MAKE) BUILD=release test

full-test: ## Run module + nginx integration suites (Phase B; pins BUILD=release)
	$(MAKE) BUILD=release full-test
else
test: $(TEST_PREREQ) ## Run the integration test suite
	@for t in $(TESTS); do \
		echo "==> $$t"; \
		env $(TEST_ENV) bash $$t || exit 1; \
	done

# Phase B will fill this in. For now it's an alias for `test`.
full-test: test ## Run module + nginx integration suites (Phase B)
endif

clean: ## Cleanup everything
	rm -rf $(NGINX_BUILD_DIR)
	$(NGX_CARGO) clean

# ── OTel collector lifecycle (wraps test-harness/lib.sh) ────────────────────
# These targets manage the local OTel collector container the integration
# tests need.  `make test` does NOT depend on `collector-up` because each
# test script auto-starts the collector via test-harness/lib.sh; but
# operators can use these for explicit control.

HARNESS_DIR	= $(CURDIR)/test-harness

.PHONY: collector-up collector-down collector-status

collector-up: ## Start the local OTel collector (idempotent)
	@bash -c '. $(HARNESS_DIR)/lib.sh && ensure_collector_running'

collector-down: ## Stop the local OTel collector
	@bash -c '. $(HARNESS_DIR)/lib.sh && collector_down'

collector-status: ## Show local OTel collector status
	@bash -c '. $(HARNESS_DIR)/lib.sh && collector_status'

# GNU make convenience targets. Will be ignored by other implementations.

build-%: ## Build with the specified configuration. E.g. make build-sanitize.
	$(MAKE) build BUILD="$*"

test-%: ## Test with the specified configuration.
	$(MAKE) test BUILD="$*"

# ── Stress gates ────────────────────────────────────────────────────────────

# Time::sleep() panic-path 1-hour watch loop.
# Default LOOP_FOR=3600 for the formal gate; override to 60 for ad-hoc runs.

.PHONY: timer-panic-watch

timer-panic-watch: ## 1-hour Time::sleep panic watch (LOOP_FOR=3600 default; override to 60 for ad-hoc)
	LOOP_FOR=$${LOOP_FOR:-3600} bash tests/bench/timer_panic_watch.sh

# TSAN: build nginx + module under ThreadSanitizer inside Docker and
# run both gRPC smoke integration scripts.  Linux arm64 only.
# Prerequisites on the host: Docker available; collector running (collector-up).
# macOS operators: `make build BUILD=tsan` still works for flag-validity checks;
# only `make tsan-test` (the dockerized run) is Linux arm64-only.

.PHONY: tsan-test tsan-test-dns tsan-test-error

tsan-test: ## TSAN build + smoke scripts in Docker (Linux arm64 only)
tsan-test: collector-up
	DOCKER_ARCH="$$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')"; \
	docker build \
	    --platform "linux/$${DOCKER_ARCH}" \
	    -f build/Dockerfile.tsan \
	    -t ngx-otel-tsan:latest \
	    .; \
	docker run --rm \
	    --network=host \
	    --cap-add=SYS_PTRACE \
	    --security-opt seccomp=unconfined \
	    --platform "linux/$${DOCKER_ARCH}" \
	    -e TSAN_OPTIONS="halt_on_error=1:second_deadlock_stack=1:detect_deadlocks=1" \
	    -e OTEL_COLLECTOR_AUTOSTART=0 \
	    -v "$(CURDIR)":/work/ngx-otel-rust \
	    -v "$(CURDIR)/../nginx":/work/nginx \
	    -v "$(CURDIR)/../ngx-rust":/work/ngx-rust \
	    -v ngx-otel-tsan-target:/work/ngx-otel-rust/target \
	    -v ngx-otel-tsan-objs:/work/ngx-otel-rust/objs-tsan \
	    -v ngx-otel-tsan-objs-plain:/work/ngx-otel-rust/objs-tsan-plain \
	    ngx-otel-tsan:latest \
	    bash /work/ngx-otel-rust/build/tsan-run.sh

tsan-test-dns: ## DNS-only TSAN gate: exercises resolver+connect path under TSAN (Linux arm64 only)
tsan-test-dns: collector-up
	DOCKER_ARCH="$$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')"; \
	docker build \
	    --platform "linux/$${DOCKER_ARCH}" \
	    -f build/Dockerfile.tsan \
	    -t ngx-otel-tsan:latest \
	    .; \
	docker run --rm \
	    --network=host \
	    --cap-add=SYS_PTRACE \
	    --security-opt seccomp=unconfined \
	    --platform "linux/$${DOCKER_ARCH}" \
	    -e TSAN_OPTIONS="halt_on_error=1:second_deadlock_stack=1:detect_deadlocks=1" \
	    -e OTEL_COLLECTOR_AUTOSTART=0 \
	    -v "$(CURDIR)":/work/ngx-otel-rust \
	    -v "$(CURDIR)/../nginx":/work/nginx \
	    -v "$(CURDIR)/../ngx-rust":/work/ngx-rust \
	    ngx-otel-tsan:latest \
	    bash /work/ngx-otel-rust/build/tsan-run-dns-only.sh

tsan-test-error: ## Error-log-only TSAN gate: exercises the coalesced error-log path under TSAN (Linux arm64 only)
tsan-test-error: collector-up
	DOCKER_ARCH="$$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')"; \
	docker build \
	    --platform "linux/$${DOCKER_ARCH}" \
	    -f build/Dockerfile.tsan \
	    -t ngx-otel-tsan:latest \
	    .; \
	docker run --rm \
	    --network=host \
	    --cap-add=SYS_PTRACE \
	    --security-opt seccomp=unconfined \
	    --platform "linux/$${DOCKER_ARCH}" \
	    -e TSAN_OPTIONS="halt_on_error=1:second_deadlock_stack=1:detect_deadlocks=1" \
	    -e OTEL_COLLECTOR_AUTOSTART=0 \
	    -v "$(CURDIR)":/work/ngx-otel-rust \
	    -v "$(CURDIR)/../nginx":/work/nginx \
	    -v "$(CURDIR)/../ngx-rust":/work/ngx-rust \
	    ngx-otel-tsan:latest \
	    bash /work/ngx-otel-rust/build/tsan-run-error-only.sh

# AddressSanitizer (ASan) gate: exercises the async-executor wake/teardown
# paths under -fsanitize=address / -Zsanitizer=address to catch use-after-free
# (the open concern on ngx-rust PR #295's always-defer change).  Linux arm64
# only — ASan needs Linux; the macOS dev box runs it via this dockerized gate.
# Reuses the Dockerfile.tsan toolchain image (clang + libclang-rt-dev provides
# the ASan runtime too).  Named volumes isolate the container's build outputs
# (target + objs-sanitize + objs-asan-plain) so the root-running build never
# pollutes host artifacts AND never reuses host-generated objs-* whose Makefiles
# bake absolute host paths (the container path /work/... differs).  ASAN_OPTIONS
# is set inside build/asan-run.sh (detect_leaks=0; UAF-focused).
.PHONY: asan-test
asan-test: ## ASan UAF gate: executor wake/teardown paths under AddressSanitizer (Linux arm64 only)
asan-test: collector-up
	DOCKER_ARCH="$$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')"; \
	docker build \
	    --platform "linux/$${DOCKER_ARCH}" \
	    -f build/Dockerfile.tsan \
	    -t ngx-otel-sanitize:latest \
	    .; \
	docker run --rm \
	    --network=host \
	    --cap-add=SYS_PTRACE \
	    --security-opt seccomp=unconfined \
	    --platform "linux/$${DOCKER_ARCH}" \
	    -e OTEL_COLLECTOR_AUTOSTART=0 \
	    -e ASAN_SCRIPTS="$(ASAN_SCRIPTS)" \
	    -v "$(CURDIR)":/work/ngx-otel-rust \
	    -v "$(CURDIR)/../nginx":/work/nginx \
	    -v "$(CURDIR)/../ngx-rust":/work/ngx-rust \
	    -v ngx-otel-asan-target:/work/ngx-otel-rust/target \
	    -v ngx-otel-asan-objs-sanitize:/work/ngx-otel-rust/objs-sanitize \
	    -v ngx-otel-asan-objs-plain:/work/ngx-otel-rust/objs-asan-plain \
	    -v ngx-otel-asan-objs-nossl:/work/ngx-otel-rust/objs-asan-nossl \
	    ngx-otel-sanitize:latest \
	    bash /work/ngx-otel-rust/build/asan-run.sh
