// Copyright (c) F5, Inc.
//
// This source code is licensed under the Apache License, Version 2.0 license found in the
// LICENSE file in the root directory of this source tree.

//! Phase 1.2 Item 2 — bidi echo server (test-only stand-alone binary).
//!
//! Implements the `Echo.BidiEcho` gRPC service: streams Ping messages back
//! as Pong replies (one-per-ping, seq copied from the ping).  Used by the
//! `run_grpc_bidi_smoke.sh` integration test as the in-process target for
//! the bidi bridge exercise.
//!
//! Phase 1.2 Item 3 extension: the `BIDI_ECHO_DELAY_MS` environment variable
//! introduces an artificial per-pong delay (default: 0 — no delay, byte-identical
//! behaviour to Item 2).  The overload integration test sets this to 10ms to
//! cap server throughput at ~100 msg/sec, creating a 10× rate mismatch against
//! the client's 1 000 msg/sec target and driving the backpressure give-up path.
//!
//! This binary:
//! - Uses Tokio (added as a dev-dependency; NEVER linked into the module dylib).
//! - Is freestanding test infrastructure; it does NOT import from `src/`.
//! - Binds to `127.0.0.1:4319` by default (override with `BIDI_ECHO_BIND`).

// Include the server+client generated code for the echo proto.
// This is the server-enabled version (OUT_DIR/echo_server_gen/) generated by
// build.rs specifically for examples.  This is a full-std binary so Box::pin
// is in scope without additional imports.
pub mod ngx_otel_echo_v1 {
    include!(concat!(env!("OUT_DIR"), "/echo_server_gen/ngx.otel.echo.v1.rs"));
}

use ngx_otel_echo_v1::{
    echo_server::{Echo, EchoServer},
    Ping, Pong,
};

use std::pin::Pin;
use std::time::Duration;
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use tokio_stream::StreamExt;
use tonic::{Request, Response, Status, Streaming};

// ── Echo service implementation ───────────────────────────────────────────────

struct EchoSvc {
    /// Per-pong artificial delay in milliseconds.  0 = no delay (default;
    /// byte-identical behaviour to Item 2).  Set via `BIDI_ECHO_DELAY_MS`.
    delay_ms: u64,
}

#[tonic::async_trait]
impl Echo for EchoSvc {
    type BidiEchoStream =
        Pin<Box<dyn tokio_stream::Stream<Item = Result<Pong, Status>> + Send + 'static>>;

    async fn bidi_echo(
        &self,
        request: Request<Streaming<Ping>>,
    ) -> Result<Response<Self::BidiEchoStream>, Status> {
        let mut inbound = request.into_inner();
        let delay_ms = self.delay_ms;

        // Channel capacity matches the 16-slot channel used on the client side
        // in fire_one_bidi_stream.  One buffer slot per in-flight ping is
        // enough at this test scale.
        let (tx, rx) = mpsc::channel::<Result<Pong, Status>>(16);

        // Spawn a task that reads each Ping and sends back a Pong.  The task
        // completes when the client closes the send-half (inbound returns None).
        tokio::spawn(async move {
            while let Some(item) = inbound.next().await {
                match item {
                    Ok(ping) => {
                        // Simulate a slow consumer when BIDI_ECHO_DELAY_MS > 0.
                        // With delay_ms = 0 (default) the branch is never taken;
                        // behaviour is byte-identical to the original Item 2 binary.
                        if delay_ms > 0 {
                            tokio::time::sleep(Duration::from_millis(delay_ms)).await;
                        }
                        let pong = Pong { seq: ping.seq, payload: ping.payload };
                        if tx.send(Ok(pong)).await.is_err() {
                            // Receiver dropped (client gone); stop silently.
                            break;
                        }
                    }
                    Err(status) => {
                        // Forward stream errors to the response so the client
                        // can surface them.
                        let _ = tx.send(Err(status)).await;
                        break;
                    }
                }
            }
            // tx drops here, closing the response stream.
        });

        let outbound = ReceiverStream::new(rx);
        Ok(Response::new(Box::pin(outbound)))
    }
}

// ── Main ──────────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // BIDI_ECHO_DELAY_MS: artificial per-pong delay in milliseconds.
    // Default 0 → no delay, byte-identical to the original Item 2 server.
    // Set to a positive value (e.g. 10) to simulate a slow consumer for the
    // Phase 1.2 Item 3 backpressure overload test.
    let delay_ms: u64 =
        std::env::var("BIDI_ECHO_DELAY_MS").ok().and_then(|s| s.parse().ok()).unwrap_or(0);

    let bind_addr =
        std::env::var("BIDI_ECHO_BIND").unwrap_or_else(|_| "127.0.0.1:4319".to_string());
    let addr: std::net::SocketAddr = bind_addr.parse()?;

    println!("bidi echo server: listening on {addr} (delay={delay_ms}ms)");

    tonic::transport::Server::builder()
        .add_service(EchoServer::new(EchoSvc { delay_ms }))
        .serve(addr)
        .await?;

    Ok(())
}
