// Copyright (c) F5, Inc.
//
// This source code is licensed under the Apache License, Version 2.0 license found in the
// LICENSE file in the root directory of this source tree.

//! Phase 1.2 Item 2 — bidi echo server (test-only stand-alone binary).
//!
//! Implements the `Echo.BidiEcho` gRPC service: streams Ping messages back
//! as Pong replies (one-per-ping, seq copied from the ping).  Used by the
//! `run_grpc_bidi_smoke.sh` integration test as the in-process target for
//! the bidi bridge exercise.
//!
//! This binary:
//! - Uses Tokio (added as a dev-dependency; NEVER linked into the module dylib).
//! - Is freestanding test infrastructure; it does NOT import from `src/`.
//! - Binds to `127.0.0.1:4319` by default (override with `BIDI_ECHO_BIND`).

// Include the server+client generated code for the echo proto.
// This is the server-enabled version (OUT_DIR/echo_server_gen/) generated by
// build.rs specifically for examples.  This is a full-std binary so Box::pin
// is in scope without additional imports.
pub mod ngx_otel_echo_v1 {
    include!(concat!(env!("OUT_DIR"), "/echo_server_gen/ngx.otel.echo.v1.rs"));
}

use ngx_otel_echo_v1::{
    Ping, Pong,
    echo_server::{Echo, EchoServer},
};

use std::pin::Pin;
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use tokio_stream::StreamExt;
use tonic::{Request, Response, Status, Streaming};

// ── Echo service implementation ───────────────────────────────────────────────

struct EchoSvc;

#[tonic::async_trait]
impl Echo for EchoSvc {
    type BidiEchoStream = Pin<Box<dyn tokio_stream::Stream<Item = Result<Pong, Status>> + Send + 'static>>;

    async fn bidi_echo(
        &self,
        request: Request<Streaming<Ping>>,
    ) -> Result<Response<Self::BidiEchoStream>, Status> {
        let mut inbound = request.into_inner();

        // Channel capacity matches the 16-slot channel used on the client side
        // in fire_one_bidi_stream.  One buffer slot per in-flight ping is
        // enough at this test scale.
        let (tx, rx) = mpsc::channel::<Result<Pong, Status>>(16);

        // Spawn a task that reads each Ping and sends back a Pong.  The task
        // completes when the client closes the send-half (inbound returns None).
        tokio::spawn(async move {
            while let Some(item) = inbound.next().await {
                match item {
                    Ok(ping) => {
                        let pong = Pong {
                            seq: ping.seq,
                            payload: ping.payload,
                        };
                        if tx.send(Ok(pong)).await.is_err() {
                            // Receiver dropped (client gone); stop silently.
                            break;
                        }
                    }
                    Err(status) => {
                        // Forward stream errors to the response so the client
                        // can surface them.
                        let _ = tx.send(Err(status)).await;
                        break;
                    }
                }
            }
            // tx drops here, closing the response stream.
        });

        let outbound = ReceiverStream::new(rx);
        Ok(Response::new(Box::pin(outbound)))
    }
}

// ── Main ──────────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let bind_addr = std::env::var("BIDI_ECHO_BIND")
        .unwrap_or_else(|_| "127.0.0.1:4319".to_string());
    let addr: std::net::SocketAddr = bind_addr.parse()?;

    println!("bidi echo server: listening on {addr}");

    tonic::transport::Server::builder()
        .add_service(EchoServer::new(EchoSvc))
        .serve(addr)
        .await?;

    Ok(())
}
